### ISSUE TITLE
Make Github Issue labels configurable/opt-in

### ISSUE THREAD

**Issue by dictvm** [m-lab/alertmanager-github-receiver#20]
Currently a new issue is created with an "alert💥"-label. However, my employer is pretty strict on custom labels because they apply to every repo in the entire organisation. It would be great if the label could be customised via parameter.

**Comment by pboothe** [comment]
Glad you like this! We happily accept pull requests, but will also put this issue into our bug triage system.

**Comment by dictvm** [comment]
Sorry, I was really joyful when I found this project, I didn't mean to be rude. Of course I should have started with some praise for how cool this tool is. We're in the middle of improving the way we do incident management SRE-style and having the option of creating issues for non-actionable alerts is awesome. 

I've already looked at the source and I think my golang skills could be barely sufficient to give this a try.

**Comment by pboothe** [comment]
Fixed! Enjoy!

**Comment by dictvm** [comment]
Greast, @pboothe! However, could you also issue a new release for this? :)

**Comment by pboothe** [comment]
https://github.com/m-lab/alertmanager-github-receiver/releases/tag/v0.7

**Comment by stephen-soltesz** [comment]
For the record: the dockerhub image name: measurementlab/alertmanager-github-receiver:v0.7
