### ISSUE TITLE
Add non-Docker instructions

### ISSUE THREAD

**Issue by Daniel15** [m-lab/alertmanager-github-receiver#22]
I don't use Docker... How can I set up this webhook receiver without configuring Docker? Can I just compile and run the code?

**Comment by stephen-soltesz** [comment]
@Daniel15 for sure!

Once you have Go installed, you can build using this command:
https://github.com/m-lab/alertmanager-github-receiver/blob/master/Dockerfile#L7

**Comment by Daniel15** [comment]
Thank you! I wasn't very familiar with compiling Go apps, but should have thought to just look in the Docker file 😅
