### ISSUE TITLE
Pass auth token via environment variable?

### ISSUE THREAD

**Issue by Daniel15** [m-lab/alertmanager-github-receiver#24]
Command line parameters (like your `authtoken`) are visible in the output of `ps`. Because of this, it's often a good idea to pass secrets like API keys as environment variables instead.

**Comment by stephen-soltesz** [comment]
This is a reasonable request. Since https://github.com/m-lab/alertmanager-github-receiver/pull/16 you can also pass the auth token by file.

**Comment by mattmathis** [comment]
ps also shows environment variables:
ps axle | cat
(the cat is needed to prevent ps from discovering the line length.  For some reason ww gives different results.)

**Comment by Daniel15** [comment]
> ps also shows environment variables:

Hmm, interesting! I wonder why so many articles say to pass secrets via environment variables...

Passing it by file (as per @stephen-soltesz' comment above) seems reasonable.

**Comment by stephen-soltesz** [comment]
This should be possible with the new version in HEAD.

`AUTHTOKEN=<foo> github_receiver <--other-flags ...>`
