### ISSUE TITLE
No default issue title

### ISSUE THREAD

**Issue by 4n4nd** [m-lab/alertmanager-github-receiver#50]
When a new issue is created by the receiver, it has a `<no title>` by default (example issue: https://github.com/operate-first/SRE/issues/36)

**Comment by stephen-soltesz** [comment]
Thank you for the report. I'll take a look.

**Comment by hemajv** [comment]
Our alert: https://github.com/operate-first/SRE/issues/36, does have the following labels:
```
Labels:

alertname = Grafana Service Down
prometheus = opf-monitoring/odh-monitoring
```
however, by default `{{ .Data.GroupLabels.alertname }}` returned `<no value>` for us. is there another way we can modify this?

**Comment by stephen-soltesz** [comment]
@4n4nd @hemajv if you're able:

* Can you provide the flags passed to the alertmanager-github-receiver command?
* What version of alertmanager are you using?
* Can you include more of the content of the alert `.Data`?

**Comment by 4n4nd** [comment]
@stephen-soltesz our Deployment args are [here](https://github.com/operate-first/apps/blob/master/odh/base/monitoring/github-receiver.yaml#L28-L34)
```yaml
          args:
            - --authtoken=$(GITHUB_AUTH_TOKEN)
            - --org=operate-first
            - --repo=SRE
            - --label=in progress
            - --enable-inmemory=false
            - --enable-auto-close=true
```
The version we are using is `v0.10`

**Comment by stephen-soltesz** [comment]
@4n4nd @hemajv

Aha. In the original design of the github-receiver, we expected `GroupLabels` to always include an `alertname` key/value. Looking back now, this was almost certainly a result of our building on example Alertmanager configs that use the `group_by` directive with `alertname` -- https://github.com/prometheus/alertmanager#example

When a different `group_by` label is used, then the `alertname` label is empty, and the default title template results in a title with "<no value>".

Is this the alertmanager config you are using?
https://github.com/operate-first/apps/blob/master/odh/base/monitoring/alertmanager-config.yaml#L10

If so, I believe this explains what's happening. You may try updating the ` -title-template-file` with a template that references `job` or updating the alertmanager config to include grouping by alertname.

**Comment by 4n4nd** [comment]
> Is this the alertmanager config you are using?

yes that is it

**Comment by hemajv** [comment]
Ah yes that is our alertmanager config. Thanks @stephen-soltesz will update it to group by `alertname`! :smiley:
