### ISSUE TITLE
Github Depreciations

### ISSUE THREAD

**Issue by rhys-evans** [m-lab/alertmanager-github-receiver#53]
HI

Not sure if this affects this tool  ?

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Thanks

**Comment by laiyi-ohlsen** [comment]
Hi @rhys-evans, @stephen-soltesz will look at this and log his findings here. Thanks for logging!

**Comment by stephen-soltesz** [comment]
@rhys-evans I'm happy to report that the alertmanager-github-receiver uses authorization headers and should be unaffected by the deprecation of authentication in query parameters.
